version: '3.1'
services:
  master:
    image: redis
    container_name: redis-master
    ports:
      - 6379:6379
    command: redis-server --replica-announce-ip 192.168.16.144 --replica-announce-port 6379

  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6380:6379
    command: redis-server --slaveof 192.168.16.144 6379 --replica-announce-ip 192.168.16.144 --replica-announce-port 6380

  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6381:6379
    command: redis-server --slaveof 192.168.16.144 6379 --replica-announce-ip 192.168.16.144 --replica-announce-port 6381
  
  sentinel1:
    image: sentinel1
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: sentinel2
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: sentinel3
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf